---
# defaults file for your_namespace.terminal.tool_installer

tool_installer_tools: []

tool_installer_definitions:
  - name: starship
    version: "1.18.0"
    description: "The minimal, blazing-fast, and infinitely customizable prompt for any shell."
    init_snippet: 'eval "$(starship init {{ shell_type_resolved }})"'
  - name: ripgrep
    version: "14.1.0"
    executable_name: "rg"
    description: "A fast line-oriented search tool."
    aliases:
      grep: "rg --color=auto"
  - name: sheldon
    version: "0.8.2"
    description: "A fast, configurable, shell plugin manager."
    init_snippet: 'eval "$(sheldon source)"'
  - name: fzf
    version: "0.62.0"
    description: "A command-line fuzzy finder."
    env_vars:
      FZF_DEFAULT_OPTS: "--height 40% --layout=reverse --border"
    init_snippet: |
      # FZF Standalone Setup
      if [ -f "$HOME/.bash_completion.d/fzf-key-bindings.bash" ]; then . "$HOME/.bash_completion.d/fzf-key-bindings.bash"; fi
      if [ -f "$HOME/.bash_completion.d/fzf-completion.bash" ]; then . "$HOME/.bash_completion.d/fzf-completion.bash"; fi
    init_snippet_zsh: |
      # FZF Standalone Setup
      if [ -f "$HOME/.zsh/completions/fzf-key-bindings.zsh" ]; then . "$HOME/.zsh/completions/fzf-key-bindings.zsh"; fi
  - name: bat
    version: "0.25.0"
    description: "A cat(1) clone with wings."
    aliases:
      cat: "bat --paging=never"
  - name: eza
    version: "0.21.4"
    description: "A modern replacement for ls."
    aliases:
      ls: "eza --group-directories-first --color=always"
      ll: "eza -l --group-directories-first --color=always"
      la: "eza -la --group-directories-first --color=always"
  - name: zoxide
    version: "0.9.8"
    description: "A smarter cd command."
    init_snippet: 'eval "$(zoxide init {{ shell_type_resolved }} --cmd z)"'
  - name: direnv
    version: "2.33.0"
    description: "An environment switcher for the shell."
    init_snippet: 'eval "$(direnv hook {{ shell_type_resolved }})"'
  - name: uv
    version: "0.7.13"
    description: "Extremely fast Python package manager."
