---
- name: Ensure bin directory exists
  ansible.builtin.file:
    path: "{{ terminal_setup_bin_dir }}"
    state: directory
    mode: '0755'
  become: false

- name: Print tools eligible for symlinking
  ansible.builtin.debug:
    msg: "Tool {{ item.name }}: binaries={{ item.binaries | length if item.binaries is defined else 'undefined' }}"
  loop: "{{ terminal_setup_tools_processed | selectattr('symlink_as', 'defined') | selectattr('state', 'eq', 'present') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Manage symlinks for tools
  ansible.builtin.file:
    src: "{{ terminal_setup_bin_dir }}/{{ item.name }}"
    dest: "{{ terminal_setup_bin_dir }}/{{ item.symlink_as }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    state: link
    force: true
  loop: "{{ terminal_setup_tools_processed | selectattr('symlink_as', 'defined') | selectattr('state', 'eq', 'present') | selectattr('binaries', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }} -> {{ item.symlink_as }}"
  when:
    - item.binaries is defined
    - item.binaries | length > 0

- name: Remove symlinks for absent tools
  ansible.builtin.file:
    path: "{{ terminal_setup_bin_dir }}/{{ item.symlink_as }}"
    state: absent
  loop: "{{ terminal_setup_tools_processed | selectattr('symlink_as', 'defined') | selectattr('state', 'eq', 'absent') | list }}"
  loop_control:
    label: "{{ item.name }} -> {{ item.symlink_as }}"
