---
- name: "SDKMAN | Check if SDKMAN is already installed"
  ansible.builtin.stat:
    path: "{{ sdkman_install_dir }}/bin/sdkman-init.sh"
  register: sdkman_init_stat

- name: "SDKMAN | Install via non-interactive script"
  ansible.builtin.shell:
    cmd: "curl -s \"{{ sdkman_install_script_url }}\" | bash"
    creates: "{{ sdkman_install_dir }}/bin/sdkman-init.sh"
  environment:
    SDKMAN_DIR: "{{ sdkman_install_dir }}"
    SDKMAN_FORCE_SELFUPDATE: "false"
    SDKMAN_NON_INTERACTIVE: "true"
  when: not sdkman_init_stat.stat.exists

- name: "SDKMAN | Ensure SDKMAN is at desired version (self-update)"
  ansible.builtin.shell: |
    # Source the init script and run self-update
    . {{ sdkman_install_dir }}/bin/sdkman-init.sh && \
    sdk selfupdate {{ sdkman_version }}
  args:
    creates: "{{ sdkman_install_dir }}/var/version"
  when:
    - sdkman_init_stat.stat.exists
    - sdkman_version != "latest"
  register: sdkman_selfupdate
  changed_when: sdkman_selfupdate.rc == 0

- name: "SDKMAN | Deploy SDKMAN init script"
  ansible.builtin.template:
    src: sdkman.sh.j2
    dest: "{{ ansible_user_dir }}/.config/shell_init.d/10-sdkman.sh"
    mode: '0755'
