---
- name: Converge
  hosts: all
  vars:
    tool_installer_tools:
      - fzf
      - ripgrep
    tool_installer_shells:
      - bash
      - zsh

  pre_tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == 'Debian'

    - name: "Install test dependencies"
      ansible.builtin.package:
        name:
          - sudo
          - curl
        state: present
      become: true

  roles:
    - role: "eddiedunn.terminal.tool_installer"
