---
- name: Verify
  hosts: all
  become: false
  vars:
    bin_dir: "{{ ansible_user_dir }}/.local/bin"
    bash_completion_dir: "{{ ansible_user_dir }}/.bash_completion.d"
    zsh_completion_dir: "{{ ansible_user_dir }}/.zsh/completions"

  tasks:
    # ------------------------------------------------------------------
    # Verify fzf installation
    # ------------------------------------------------------------------
    - name: "Verify | fzf binary symlink exists"
      ansible.builtin.stat:
        path: "{{ bin_dir }}/fzf"
      register: fzf_binary
      failed_when: not fzf_binary.stat.islnk

    - name: "Verify | fzf bash completion exists"
      ansible.builtin.stat:
        path: "{{ bash_completion_dir }}/fzf.bash"
      register: fzf_bash_completion
      failed_when: not fzf_bash_completion.stat.exists

    - name: "Verify | fzf zsh completion exists"
      ansible.builtin.stat:
        path: "{{ zsh_completion_dir }}/_fzf"
      register: fzf_zsh_completion
      failed_when: not fzf_zsh_completion.stat.exists

    # ------------------------------------------------------------------
    # Verify ripgrep installation
    # ------------------------------------------------------------------
    - name: "Verify | ripgrep (rg) binary symlink exists"
      ansible.builtin.stat:
        path: "{{ bin_dir }}/rg"
      register: rg_binary
      failed_when: not rg_binary.stat.islnk

    - name: "Verify | ripgrep bash completion exists"
      ansible.builtin.stat:
        path: "{{ bash_completion_dir }}/rg.bash"
      register: rg_bash_completion
      failed_when: not rg_bash_completion.stat.exists

    - name: "Verify | ripgrep zsh completion exists"
      ansible.builtin.stat:
        path: "{{ zsh_completion_dir }}/_rg"
      register: rg_zsh_completion
      failed_when: not rg_zsh_completion.stat.exists
