---
- name: Verify (Minimal)
  hosts: all
  become: true
  vars:
    user_home: "{{ ansible_facts.get('user_dir', ansible_user_dir) }}"
    enabled_tools:
      - fzf
      - bat
    disabled_tools:
      - starship
      - sheldon
      - eza
      - zoxide
      - direnv
  tasks:
    - name: Block for Verifying Enabled Tools
      block:
        - name: Verify enabled binaries are installed
          ansible.builtin.stat:
            path: "{{ user_home }}/.local/bin/{{ item }}"
          register: binary_stat
          loop: "{{ enabled_tools }}"
          loop_control:
            label: "{{ item }}"

        - name: Assert enabled binaries are installed and executable
          ansible.builtin.assert:
            that:
              - binary_stat.stat.exists
              - binary_stat.stat.executable
          loop: "{{ enabled_tools }}"
          loop_control:
            label: "{{ item }}"

    - name: Block for Verifying Disabled Tools
      block:
        - name: Verify disabled binaries are NOT installed
          ansible.builtin.stat:
            path: "{{ user_home }}/.local/bin/{{ item }}"
          register: binary_stat
          loop: "{{ disabled_tools }}"
          loop_control:
            label: "{{ item }}"

        - name: Assert disabled binaries are NOT installed
          ansible.builtin.assert:
            that:
              - not binary_stat.stat.exists
          loop: "{{ disabled_tools }}"
          loop_control:
            label: "{{ item }}"

    - name: Block for Verifying Completions
      block:
        - name: Verify completions for enabled tools exist
          ansible.builtin.stat:
            path: "{{ user_home }}/.bash_completion.d/{{ item }}"
          register: completion_stat
          loop:
            - fzf.bash
            - bat.bash
          loop_control:
            label: "{{ item }}"

        - name: Assert completions for enabled tools exist
          ansible.builtin.assert:
            that:
              - completion_stat.stat.exists
          loop:
            - fzf.bash
            - bat.bash
          loop_control:
            label: "{{ item }}"

        - name: Verify completions for disabled tools do NOT exist
          ansible.builtin.stat:
            path: "{{ user_home }}/.bash_completion.d/{{ item }}"
          register: completion_stat
          loop:
            - starship.bash
            - sheldon.bash
            - eza.bash
            - zoxide.bash
            - direnv.bash
          loop_control:
            label: "{{ item }}"

        - name: Assert completions for disabled tools do NOT exist
          ansible.builtin.assert:
            that:
              - not completion_stat.stat.exists
          loop:
            - starship.bash
            - sheldon.bash
            - eza.bash
            - zoxide.bash
            - direnv.bash
          loop_control:
            label: "{{ item }}"
