---
# tasks/main.yml for eddiedunn.terminal.profile
# This meta-role orchestrates the other roles in the collection.

- name: "1. Install system-level dependencies for tools"
  ansible.builtin.include_role:
    name: eddiedunn.terminal.system_dependencies
  vars:
    system_dependencies_tools: "{{ profile_tools }}"
  when: profile_tools | length > 0

- name: "2. Set up base user environment and shell chassis"
  ansible.builtin.include_role:
  vars:
    profile_tools: "{{ profile_tools }}" # Pass for conditional logic (e.g., sheldon)

- name: "3. Install binary-based tools via the tool_installer"
  ansible.builtin.include_role:
    name: eddiedunn.terminal.tool_installer
  vars:
    tool_installer_tools: "{{ profile_tools }}"
    tool_installer_shells: "{{ profile_shells }}"

- name: "4. Install NVM if requested"
  ansible.builtin.include_role:
    name: eddiedunn.terminal.nvm
  when: "'nvm' in profile_tools"

- name: "5. Install Pyenv if requested"
  ansible.builtin.include_role:
    name: eddiedunn.terminal.pyenv
  when: "'pyenv' in profile_tools"

- name: "6. Install Rustup if requested"
  ansible.builtin.include_role:
    name: eddiedunn.terminal.rustup
  when: "'rustup' in profile_tools"
