---
- name: "Clone NVM repository"
  ansible.builtin.git:
    repo: "{{ nvm_git_repo }}"
    dest: "{{ ansible_user_dir }}/.nvm"
    version: "{{ nvm_version }}"
    force: false

- name: "Deploy NVM init script"
  ansible.builtin.template:
    src: nvm.sh.j2
    dest: "{{ ansible_user_dir }}/.config/shell_init.d/10-nvm.sh"
    mode: '0755'
