namespace: eddiedunn
name: terminal
version: 1.0.0
readme: README.md
authors:
  - 'Ansible User <user@example.com>'
description: >-
  Modular Ansible collection to configure a modern, cross-platform terminal environment with userland tools, dotfiles, and developer shell workflows.
license:
  - MIT
tags:
  - tools
  - terminal
  - shell
  - zsh
  - bash
  - starship
  - sheldon
  - development
  - dotfiles
dependencies: {}
repository: 'https://github.com/example/terminal'
homepage: 'https://github.com/example/terminal'
issues: 'https://github.com/example/terminal/issues'
build_ignore:
  - .git
  - .gitignore
  - '*.tar.gz'
  - 'molecule/'
