namespace: oreillyauto
name: terminal
version: 1.0.0
readme: README.md
authors:
  - gdunn6 <gdunn6@oreillyauto.com>
description: A simple, hybrid approach to modern terminal environment setup
license:
  - MIT
license_file: ''
tags:
  - terminal
  - development
  - tools
  - homebrew
  - shell
  - productivity
dependencies: {}
repository: https://bitbucket.org/oreillyauto/gdunn6_ansible
documentation: https://bitbucket.org/oreillyauto/gdunn6_ansible
homepage: https://bitbucket.org/oreillyauto/gdunn6_ansible
issues: https://bitbucket.org/oreillyauto/gdunn6_ansible/issues
build_ignore: []
