---
- name: Test Refactored Terminal Collection
  hosts: localhost
  connection: local
  vars:
    profile_tools:
      - starship
      - fzf
      - bat
      - nvm
      - rustup
  roles:
    - role: profile # The profile role orchestrates everything
