---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
    command: ""
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: testuser
verifier:
  name: ansible
