---
- name: Verify
  hosts: all
  become: false
  tasks:
    - name: "Set user_home fact"
      ansible.builtin.set_fact:
        user_home: "{{ ansible_user_dir }}"

    - name: "Verify core directories exist"
      ansible.builtin.stat:
        path: "{{ user_home }}/{{ item }}"
      register: dir_check
      failed_when: not dir_check.stat.exists or not dir_check.stat.isdir
      loop:
        - ".local/bin"
        - ".config/shell_init.d"
        - ".bash_completion.d"
        - ".zsh/completions"
        - ".config/fish/completions"

    - name: "Verify PATH management script exists"
      ansible.builtin.stat:
        path: "{{ user_home }}/.config/shell_init.d/00_path.sh"
      register: path_script
      failed_when: not path_script.stat.exists

    - name: "Verify shell profiles source shell_init.d"
      ansible.builtin.lineinfile:
        path: "{{ user_home }}/{{ item }}"
        line: 'if [ -d "$HOME/.config/shell_init.d" ]; then'
        state: present
      check_mode: true
      register: source_check
      failed_when: source_check.changed
      loop:
        - ".bashrc"
        - ".zshrc"
        - ".profile"

    - name: "Check idempotence"
      ansible.builtin.include_role:
        name: "eddiedunn.terminal.env_chassis"
      register: second_run

    - name: "Assert idempotence"
      ansible.builtin.assert:
        that: not second_run.changed
        fail_msg: "Role is not idempotent"
        success_msg: "Role is idempotent"
