---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    # Use docker by default, fall back to podman if available
    executable: "auto"

platforms:
  - name: instance
    # Use a basic Ubuntu image without systemd
    image: ubuntu:22.04
    pre_build_image: true
    # Keep the container running
    command: sleep infinity
    # Environment variables for Ansible
    environment:
      # Configure Ansible settings
      ANSIBLE_REMOTE_TEMP: /tmp/ansible
      ANSIBLE_REMOTE_USER: root
      ANSIBLE_RETRY_FILES_ENABLED: false
      # Disable pipelining to avoid potential issues
      ANSIBLE_PIPELINING: false
      # Enable color output
      ANSIBLE_FORCE_COLOR: '1'

provisioner:
  name: ansible
  config_options:
    defaults:
      # Use auto_silent to avoid warnings about Python interpreter
      interpreter_python: auto_silent
      # Use a temporary directory that exists in the container
      remote_tmp: /tmp/ansible
      # Ensure the remote tmp directory has correct permissions
      remote_tmp_mode: '0700'
      # Disable host key checking for testing
      host_key_checking: False
      # Disable retry files to avoid permission issues
      retry_files_enabled: False
      # Set fact caching to memory to avoid filesystem issues
      fact_caching: memory
      # Disable fact gathering for performance
      gather_subset: '!all'
      # Disable fact caching
      fact_caching_connection: ''
    ssh_connection:
      # Disable pipelining to avoid potential issues
      pipelining: False
      # Set the control path to a location with write permissions
      control_path: '/tmp/ansible-ssh-%%h-%%p-%%r'
  inventory:
    group_vars:
      all:
        # Set shell type to bash (even though Alpine uses ash by default)
        shell_type: bash
        # Explicitly set Python interpreter
        ansible_python_interpreter: /usr/bin/python3
        # Use docker connection
        ansible_connection: docker
        # Run as root in the container
        ansible_user: root

verifier:
  name: ansible
  # Disable verifier for now to simplify testing
  enabled: false
