---
# tasks/main.yml for eddiedunn.terminal.tool_installer

- name: "Set architecture fact for installer"
  ansible.builtin.set_fact:
    ansible_architecture_normalized: "{{ 'aarch64' if ansible_architecture in ['aarch64', 'arm64'] else 'x86_64' }}"

- name: "Filter for binary tools to be installed by this role"
  ansible.builtin.set_fact:
    tools_to_install: >-
      {{ tool_installer_all_definitions
          | selectattr('name', 'in', tool_installer_tools)
          | selectattr('install_type', 'eq', 'binary')
          | selectattr('binaries.' + ansible_system + '.' + ansible_architecture_normalized, 'defined')
          | list }}

- name: "Install each selected tool"
  ansible.builtin.include_tasks: "install_tool.yml"
  loop: "{{ tools_to_install }}"
  loop_control:
    loop_var: tool
