---
- name: "Find staged completion files for {{ tool.name }} on controller"
  ansible.builtin.find:
    paths: "{{ role_path }}/files/completions/"
    patterns: "{{ tool.name }}.*,*{{ tool.name }}*,_{{ tool.name }}"
    recurse: true
  register: found_completions
  delegate_to: localhost

- name: "Deploy completion files for {{ tool.name }}"
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ ansible_user_dir }}/{{ completion_dirs_map[item.path | dirname | basename] }}/{{ item.path | basename }}"
    mode: '0644'
  loop: "{{ found_completions.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  when: "(item.path | dirname | basename) in tool_installer_shells"
