---
- name: Ensure shell_init.d directory exists
  ansible.builtin.set_fact:
    shell_init_dir: "{{ ansible_user_dir }}/.config/shell_init.d"

- name: Ensure shell init directory exists
  ansible.builtin.file:
    path: "{{ shell_init_dir }}"
    state: directory
    mode: '0755'

- name: "Deploy shell init snippets for {{ tool.name }}"
  ansible.builtin.template:
    src: tool_init.sh.j2
    dest: "{{ ansible_user_dir }}/.config/shell_init.d/{{ 99 - (loop.index | default(99)) }}_{{ tool.name }}.bash"
    mode: '0644'
  vars:
    current_init_snippet: "{{ tool.init_snippet | replace('{shell_type_resolved}', 'bash') }}"
  when: "'bash' in tool_installer_shells and tool.init_snippet is defined"

- name: "Deploy Zsh init snippet for {{ tool.name }}"
  ansible.builtin.template:
    src: tool_init.sh.j2
    dest: "{{ ansible_user_dir }}/.config/shell_init.d/{{ 99 - (loop.index | default(99)) }}_{{ tool.name }}.zsh"
    mode: '0644'
  vars:
    current_init_snippet: "{{ (tool.init_snippet_zsh | default(tool.init_snippet)) | replace('{shell_type_resolved}', 'zsh') }}"
  when: "'zsh' in tool_installer_shells"
