---
- name: Verify
  hosts: all
  become: false
  vars:
    pyenv_dir: "{{ ansible_user_dir }}/.pyenv"
  tasks:
    - name: "Verify .pyenv directory exists and is a directory"
      ansible.builtin.stat:
        path: "{{ pyenv_dir }}"
      register: pyenv_dir_stat
      failed_when: not pyenv_dir_stat.stat.exists or not pyenv_dir_stat.stat.isdir

    - name: "Verify .pyenv is a git repository"
      ansible.builtin.stat:
        path: "{{ pyenv_dir }}/.git"
      register: pyenv_git_stat
      failed_when: not pyenv_git_stat.stat.exists or not pyenv_git_stat.stat.isdir

    - name: "Verify pyenv init script exists"
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.config/shell_init.d/10-pyenv.sh"
      register: pyenv_init_script
      failed_when: not pyenv_init_script.stat.exists

    - name: "Check idempotence"
      ansible.builtin.include_role:
        name: "eddiedunn.terminal.pyenv"
      register: second_run

    - name: "Assert idempotence"
      ansible.builtin.assert:
        that: not second_run.changed
        fail_msg: "Role is not idempotent"
        success_msg: "Role is idempotent"
