---
# Manage Sheldon plugin manager configuration and lock file

- name: Ensure Sheldon plugins directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/sheldon"
    state: directory
    mode: '0755'

- name: Deploy Sheldon plugins configuration
  ansible.builtin.template:
    src: sheldon_plugins.toml.j2
    dest: "{{ ansible_user_dir }}/.config/sheldon/plugins.toml"
    mode: '0644'
  register: sheldon_config_updated

- name: Update Sheldon lock file
  ansible.builtin.command:
    cmd: sheldon lock --update
    chdir: "{{ ansible_user_dir }}"
  environment:
    SHELL: "{{ ansible_env.SHELL | default('/bin/zsh') }}"
  when: sheldon_config_updated is changed
  register: sheldon_lock_updated
  changed_when: sheldon_lock_updated.rc == 0
  failed_when: sheldon_lock_updated.rc != 0
  become: false
  # noqa: no-handler

- name: Set Sheldon lock file permissions
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/sheldon/plugins.lock"
    mode: '0644'
  when: sheldon_lock_updated is defined and sheldon_lock_updated is changed
  become: false
