---
# tasks/manage_rustup.yml
# Included from main.yml for tools with install_type == 'rustup'

- name: Manage rustup installation
  block:
    - name: Install dependencies for rustup
      ansible.builtin.package:
        name: "{{ tool.dependencies[ansible_os_family] }}"
        state: present
      become: "{{ ansible_os_family != 'Darwin' }}"
      when:
        - tool.dependencies is defined
        - tool.dependencies[ansible_os_family] is defined

    - name: Check if rustup is already installed
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.cargo/bin/rustup"
      register: rustup_binary_stat

    - name: Download rustup-init script
      ansible.builtin.get_url:
        url: "{{ tool.installer_url }}"
        dest: "/tmp/rustup-init.sh"
        mode: '0755'
        force: true
      when: not rustup_binary_stat.stat.exists
      register: rustup_download_result

    - name: Install rustup (if not present)
      ansible.builtin.command:
        cmd: "/tmp/rustup-init.sh -y --no-modify-path"
      environment:
        CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
        RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
      when: not rustup_binary_stat.stat.exists
      register: rustup_install_result
      changed_when: rustup_install_result.rc == 0
