---
- name: Converge
  hosts: all
  vars:
    profile_tools:
      - starship
      - fzf
      - nvm
      - ripgrep
    profile_shells:
      - bash
      - zsh
    tool_installer_all_definitions: "{{ (lookup('file', '../../tool_installer/defaults/main.yml') | from_yaml).tool_installer_all_definitions }}"
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == 'Debian'
  roles:
    - role: "eddiedunn.terminal.profile"
