---
- name: Verify
  hosts: all
  become: false
  vars:
    bin_dir: "{{ ansible_user_dir }}/.local/bin"
    nvm_dir: "{{ ansible_user_dir }}/.nvm"
  tasks:
    - name: "Verify binaries for profile tools exist"
      ansible.builtin.stat:
        path: "{{ bin_dir }}/{{ item }}"
      register: bin_stat
      failed_when: not bin_stat.stat.exists
      loop:
        - starship
        - fzf
        - rg

    - name: "Verify nvm installation"
      ansible.builtin.stat:
        path: "{{ nvm_dir }}/nvm.sh"
      register: nvm_stat
      failed_when: not nvm_stat.stat.exists

    - name: "Verify shell init snippets exist"
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.config/shell_init.d/{{ item }}"
      register: init_stat
      failed_when: not init_stat.stat.exists
      loop:
        - "50_starship.bash"
        - "50_starship.zsh"
        - "98_fzf.bash"
        - "98_fzf.zsh"
        - "10-nvm.sh"

    - name: "Verify completion files exist"
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/{{ item }}"
      register: completion_stat
      failed_when: not completion_stat.stat.exists
      loop:
        - ".bash_completion.d/fzf-completion.bash"
        - ".bash_completion.d/fzf-key-bindings.bash"
        - ".zsh/completions/_fzf"
        - ".zsh/completions/fzf-key-bindings.zsh"

    - name: "Check idempotence"
      ansible.builtin.include_role:
        name: "eddiedunn.terminal.profile"
      register: second_run

    - name: "Assert idempotence"
      ansible.builtin.assert:
        that: not second_run.changed
        fail_msg: "Role is not idempotent"
        success_msg: "Role is idempotent"
