---
- name: Download rustup-init script
  ansible.builtin.get_url:
    url: "{{ rustup_install_url }}"
    dest: "/tmp/rustup-init.sh"
    mode: '0755'
    force: true

- name: Install rustup (if not present)
  ansible.builtin.command:
    cmd: "/tmp/rustup-init.sh -y"
  args:
    creates: "{{ ansible_user_dir }}/.cargo/bin/rustup"

- name: "Deploy rustup init script"
  ansible.builtin.template:
    src: rustup.sh.j2
    dest: "{{ ansible_user_dir }}/.config/shell_init.d/10-rustup.sh"
    mode: '0755'
