---
- name: "Set platform-specific binary facts for {{ tool.name }}"
  ansible.builtin.set_fact:
    tool_bin_src: >-
      {{ role_path }}/files/{{ ansible_system | lower }}/{{ ansible_architecture_normalized }}/{{ tool.name }}/{{ tool.version }}/
      {{ tool.executable_name | default(tool.name) }}-{{ tool.version }}
    tool_bin_dest: "{{ ansible_user_dir }}/.local/bin/{{ tool_executable_name | default(tool.name) }}"

- name: "Check if pre-downloaded binary exists for {{ tool.name }}"
  ansible.builtin.stat:
    path: "{{ tool_bin_src }}"
  register: tool_bin_stat
  delegate_to: localhost

- name: "Copy {{ tool.name }} binary to user's bin directory"
  ansible.builtin.copy:
    src: "{{ tool_bin_src }}"
    dest: "{{ tool_bin_dest }}"
    mode: '0755'
  when: tool_bin_stat.stat.exists
