---
# defaults file for eddiedunn.terminal.go

go_version: "1.22.5"
go_os: "{{ 'darwin' if ansible_system == 'Darwin' else 'linux' }}"
go_arch: "{{ 'arm64' if ansible_architecture_normalized == 'aarch64' else 'amd64' }}"
go_download_url: "https://go.dev/dl/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz"

# Standard Go environment paths
go_root: "{{ ansible_user_dir }}/.local/go"
go_path: "{{ ansible_user_dir }}/go"
go_bin: "{{ go_path }}/bin"
