---
- name: Converge
  hosts: all
  become: true
  vars:
    system_dependencies_all_definitions:
      - name: starship
        version: "1.18.0"
        description: "The minimal, blazing-fast, and infinitely customizable prompt for any shell."
        install_type: binary
        binaries:
          Darwin:
            aarch64:
              url: "https://github.com/starship/starship/releases/download/v1.18.0/starship-aarch64-apple-darwin.tar.gz"
              executable_in_archive: "starship"
      - name: ripgrep
        version: "14.1.0"
        install_type: binary
        binaries:
          Darwin:
            aarch64:
              url: "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-aarch64-apple-darwin.tar.gz"
              executable_in_archive: "rg"
          Linux:
            x86_64:
              url: "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-x86_64-unknown-linux-musl.tar.gz"
              executable_in_archive: "rg"
      - name: sheldon
        version: "0.8.2"
        install_type: binary
        binaries:
          Darwin:
            aarch64:
              url: "https://github.com/rossmacarthur/sheldon/releases/download/0.8.2/sheldon-0.8.2-aarch64-apple-darwin.tar.gz"
              executable_in_archive: "sheldon"
      - name: fzf
        version: "0.62.0"
        install_type: binary
        binaries:
          Darwin:
            aarch64:
              url: "https://github.com/junegunn/fzf/releases/download/v0.62.0/fzf-0.62.0-darwin_arm64.tar.gz"
              executable_in_archive: "fzf"
    system_dependencies_tools:
      - pyenv
      - nvm
  roles:
    - role: eddiedunn.terminal.system_dependencies
