---
# Example playbook for setting up terminal environment locally
# This demonstrates the oreillyauto.terminal collection usage

- name: "Setup Terminal Environment"
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    # Choose profile: minimal, developer, or full
    terminal_profile: "developer"
    
    # Optional: Add custom tools to the profile
    terminal_profile_custom_basic_tools: []
    # terminal_profile_custom_basic_tools:
    #   - "htop"
    #   - "tree"
    
    # Optional: Add custom language managers
    terminal_profile_custom_language_managers: []
    # terminal_profile_custom_language_managers:
    #   - name: "rbenv"
    #     method: "curl"
    #     url: "https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer"
    
    # Optional: Configure script repositories (only used with 'full' profile)
    script_repositories: []
    # script_repositories:
    #   - name: "personal_scripts"
    #     repo: "git@github.com:user/scripts.git"
    #     path_in_repo: "bin"
    #     version: "main"
    
    # Optional: Customize shell configuration
    # shell_config_shells: ["zsh", "bash"]  # Default: ["zsh"]
    # shell_aliases:
    #   ll: "eza -la"
    #   grep: "rg"
    
  tasks:
    - name: "Setup terminal profile"
      ansible.builtin.include_role:
        name: oreillyauto.terminal.terminal_profile
