---
- name: Test terminal_setup role with master enable off
  hosts: all
  vars:
    ansible_user_dir: "/home/testuser"

  roles:
    - role: terminal_setup
      vars:
        # Master switch is off, so no tools should be installed regardless of the tools list
        terminal_setup_enabled: false
        terminal_setup_profile_tools:
          - starship
          - sheldon
          - fzf
          - bat
          - eza
          - zoxide
          - direnv
